"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['AppEntry.py']
#DATA_FILES = ['Wrote', 'setup.py']
DATA_FILES = ['setup.py']
OPTIONS = {'argv_emulation': False,
            "packages":["lxml"],
            "includes":["gzip"],
            "resources":["stockDB10.db"]}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
