/* SQLEditor (SQLite)*/

CREATE TABLE priceUpdateRecord
(
uID INTEGER PRIMARY KEY  AUTOINCREMENT,
Y INTEGER,
M INTEGER,
stkID INTEGER
);

CREATE TABLE saleUpdateRecord
(
uID INTEGER PRIMARY KEY  AUTOINCREMENT,
Y INTEGER,
M INTEGER
);

CREATE TABLE divUpdateRecord
(
uID INTEGER PRIMARY KEY  AUTOINCREMENT,
Y INTEGER
);

CREATE TABLE stockShortName
(
stkID INTEGER PRIMARY KEY,
shortName TEXT
);

CREATE TABLE stock
(
stkID INTEGER NOT NULL PRIMARY KEY  REFERENCES stockShortName (stkID),
name TEXT,
chairman TEXT,
president TEXT,
buildDate TEXT,
publicDate TEXT
);

CREATE TABLE Dividend
(
dID TEXT NOT NULL PRIMARY KEY,
Y INTEGER,
stkID INTEGER NOT NULL REFERENCES stock (stkID)  ON DELETE RESTRICT ON UPDATE CASCADE,
cashDiv NUMERIC,
stokDiv NUMERIC
);

CREATE TABLE Price
(
pID TEXT NOT NULL PRIMARY KEY,
Y INTEGER,
M INTEGER,
stkID INTEGER NOT NULL REFERENCES stock (stkID)  ON DELETE RESTRICT ON UPDATE CASCADE,
price NUMERIC
);

CREATE TABLE CashFlow
(
fID TEXT NOT NULL PRIMARY KEY,
Y INTEGER,
Q INTEGER,
stkID INTEGER NOT NULL REFERENCES stock (stkID)  ON DELETE RESTRICT ON UPDATE CASCADE,
opCF NUMERIC,
invCF NUMERIC,
finanCF NUMERIC
);

CREATE TABLE Balance
(
bID TEXT NOT NULL PRIMARY KEY,
Y INTEGER,
Q INTEGER,
stkID INTEGER NOT NULL REFERENCES stock (stkID)  ON DELETE RESTRICT ON UPDATE CASCADE,
curAsset NUMERIC,
investment NUMERIC,
fixAsset NUMERIC,
intAsset NUMERIC,
otherAsset NUMERIC,
totAsset NUMERIC,
curLbts NUMERIC,
longLbts NUMERIC,
otherLbts NUMERIC,
totLbts NUMERIC,
capital NUMERIC,
additionalPaidInCap NUMERIC,
retainEarning NUMERIC,
equity NUMERIC,
bvps NUMERIC
);

CREATE TABLE Sale
(
sID TEXT NOT NULL PRIMARY KEY,
Y INTEGER,
M INTEGER,
stkID INTEGER NOT NULL REFERENCES stock (stkID)  ON DELETE RESTRICT ON UPDATE CASCADE,
Sales NUMERIC
);

CREATE TABLE balanceUpdateRecord
(
uID INTEGER PRIMARY KEY  AUTOINCREMENT,
Y INTEGER,
Q INTEGER
);

CREATE TABLE cashUpdateRecord
(
uID INTEGER PRIMARY KEY  AUTOINCREMENT,
Y INTEGER,
Q INTEGER,
stkID INTEGER
);

CREATE TABLE incomeUpdateRecord
(
uID INTEGER PRIMARY KEY  AUTOINCREMENT,
Y INTEGER,
Q INTEGER
);

CREATE TABLE Income
(
iID TEXT NOT NULL PRIMARY KEY,
Y INTEGER,
Q INTEGER,
stkID INTEGER NOT NULL REFERENCES stock (stkID)  ON DELETE RESTRICT ON UPDATE CASCADE,
stkType INTEGER,
sales NUMERIC,
cost NUMERIC,
profit NUMERIC,
expense NUMERIC,
OpIncome NUMERIC,
NonOpIncome NUMERIC,
NonOpExp NUMERIC,
PreTaxIncome NUMERIC,
TaxExp NUMERIC,
NetIncome NUMERIC,
cumeps NUMERIC,
eps NUMERIC,
epsTTM NUMERIC
);

